### PR TITLE
Re-write checkerror

### PR DESCRIPTION
**Pull request by maghuro**
UNTESTED

### CODE REVIEW

**Comment by h0me5k1n** [comment]
I don't think I can use this. Not supported in sh?

```
x@x/jffs/scripts/nordvpnmanager# my_function()
> {
>     echo "This function is ${FUNCNAME[0]}"    
> }
```
I get this

> -sh: syntax error: bad substitution

**Comment by maghuro** [comment]
Yes, sorry, only on bash.
Revert please.

**Comment by h0me5k1n** [comment]
@maghuro I already did :D 
Thanks for the input though! Never used git before... gave me a bit of experience today checking a contribution and reverting a pull request ;)

**Comment by maghuro** [comment]
Well, that was my objective! I already knew that this won't going to work, but I wanted you to learn how to revert a commit... (Just kidding) :P

**Pull request merged**
